name: easy_bill_clean_architecture
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  simple_barcode_scanner: ^0.2.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  go_router: ^14.6.2
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  intl: ^0.20.1
  signature: ^5.5.0
  async_preferences: ^1.0.1
  url_launcher: ^6.3.1
  dotted_border: ^2.1.0
  sqflite: ^2.4.1
  path: ^1.9.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - images/
    - fonts/Roboto-Regular.ttf
    - fonts/Roboto-Bold.ttf
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto-bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
